spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        include: "*"

  endpoint:
    prometheus:
      access: unrestricted

  prometheus:
    metrics:
      export:
        enabled: true